title: 基于qemu从0开始构建嵌入式linux系统
description: Quard Star tutorial with GitHub Pages.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/QQxiaoming/quard_star_tutorial"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
