name: APP_CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/app_ci.yml'
      - 'target_root_app/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/app_ci.yml'
      - 'target_root_app/**'

  workflow_dispatch:

jobs:
  main_build:
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install prerequisites
        shell: bash -l {0}
        run: |
          sudo apt update
          sudo apt install -y wget device-tree-compiler ninja-build git build-essential          \
                pkg-config zlib1g-dev libglib2.0-0 libglib2.0-dev libsdl1.2-dev libpixman-1-dev  \
                libfdt-dev autoconf automake libtool librbd-dev libaio-dev flex                  \
                bison make cmake gcc python3 ninja-build vim swig python3-dev libedit-dev        \
                libncurses5-dev liblzma-dev lua5.3 liblua5.3-dev libxml2-dev doxygen graphviz    \
                ninja-build pkg-config libglib2.0-dev libpixman-1-dev libgtk-3-dev libcap-ng-dev \
                libattr1-dev device-tree-compiler bison flex gperf
          conda create -n build_x11_env python=3.8.10 -y

      - name: Cache toolchain
        uses: actions/cache@v2
        env:
          cache-name: cache-toolchain
        with:
          path: |
            /opt/gcc-riscv64-unknown-linux-gnu
            /opt/gcc-riscv64-unknown-elf
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Download and extract prebuilt toolchain
        shell: bash -l {0}
        run: |
          RISCV_GLIBC_TOOLCHAIN=/opt/gcc-riscv64-unknown-linux-gnu
          RISCV_NEWLIBC_TOOLCHAIN=/opt/gcc-riscv64-unknown-elf
          if [ ! -d "$RISCV_GLIBC_TOOLCHAIN" ]; then
            # download prebuilt toolchain
            wget https://github.com/riscv/riscv-gnu-toolchain/releases/download/2021.08.07/riscv64-glibc-ubuntu-20.04-nightly-2021.08.07-nightly.tar.gz
            tar -xzf riscv64-glibc-ubuntu-20.04-nightly-2021.08.07-nightly.tar.gz
            mv riscv $RISCV_GLIBC_TOOLCHAIN
            rm -f *.tar.gz
            # strip binaries
            cd $RISCV_GLIBC_TOOLCHAIN
            set +e
            for i in `find libexec bin -type f`
            do
              strip -s $i
            done
            cd -
            $RISCV_GLIBC_TOOLCHAIN/bin/riscv64-unknown-linux-gnu-gcc -v
          fi
          if [ ! -d "$RISCV_NEWLIBC_TOOLCHAIN" ]; then
            # download prebuilt toolchain
            wget https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.12/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
            tar -xzf riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
            mv riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14 $RISCV_NEWLIBC_TOOLCHAIN
            rm -f *.tar.gz
            # strip binaries
            cd $RISCV_NEWLIBC_TOOLCHAIN
            set +e
            for i in `find libexec bin -type f`
            do
              strip -s $i
            done
            cd -
            $RISCV_NEWLIBC_TOOLCHAIN/bin/riscv64-unknown-elf-gcc -v
          fi

      - name: Build make
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh make

      - name: Build ncurses
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh ncurses

      - name: Build bash
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh bash

      - name: Build sudo
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh sudo

      - name: Build screenfetch
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh screenfetch

      - name: Build tree
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh tree

      - name: Build libevent
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libevent

      - name: Build screen
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh screen

      - name: Build cu
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh cu

      - name: Build libmnl
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libmnl

      - name: Build ethtool
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh ethtool

      - name: Build zlib
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh zlib

      - name: Build openssl
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh openssl

      - name: Build libpng
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libpng

      - name: Build freetype
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh freetype

      - name: Build libuuid
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libuuid

      - name: Build libx11
        shell: bash -l {0}
        run: |
          cd target_root_app
          conda activate build_x11_env
          ./build.sh libx11

      - name: Build cups
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh cups

      - name: Build libxml2
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libxml2

      - name: Build fontconfig
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh fontconfig

      - name: Build libffi
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libffi

      - name: Build alsa_lib
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh alsa_lib

      - name: Build alsa_utils
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh alsa_utils

      - name: Build openjdk_zero
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh openjdk_zero

      - name: Build lzo
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh lzo

      - name: Build attr
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh attr

      - name: Build mtd_utils
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh mtd_utils

      - name: Build dtc
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh dtc

      - name: Build trace_cmd
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh trace_cmd

      - name: Build lrzsz
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh lrzsz

      - name: Build libexpat
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libexpat

      - name: Build libdaemon
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh libdaemon

      - name: Build avahi
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh avahi

      - name: Build iperf3
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh iperf3

      - name: Build qt
        shell: bash -l {0}
        run: |
          cd target_root_app
          ./build.sh qt

      - name: Packet all
        shell: bash -l {0}
        run: |
          cd target_root_app
          rm -rf host_output/opt/jdk-10
          mv host_output host_tools
          mv output target_sysroot
          tar -czf host_tools.tar.gz host_tools/
          tar -czf target_sysroot.tar.gz target_sysroot/
          mv host_tools.tar.gz ../host_tools.tar.gz
          mv target_sysroot.tar.gz ../target_sysroot.tar.gz

      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: release
          path: |
            host_tools.tar.gz
            target_sysroot.tar.gz
