name: macos

on:
  workflow_run:
    workflows: ["MAIN_CI"]
    branches: [main]
    types:
      - completed

jobs:
  release_macos:
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: main_ci.yml
          workflow_conclusion: success
          name: output

      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: main_ci.yml
          workflow_conclusion: success
          name: qemu_macos

      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          workflow: main_ci.yml
          workflow_conclusion: success
          name: quard_star_tools_macos

      - name: release_packet
        shell: bash -l {0}
        run: |
          tar -xzvf output.tar.gz
          tar -xzvf quard_star_tools.tar.gz
          tar -xzvf qemu_macos.tar.gz
          rm -rf output.tar.gz quard_star_tools.tar.gz
          rm -rf output/busybox output/qemu
          rm -rf ./gui_tools/quard_star_tools_macos/._quard_star_tools.dmg
          rm -rf ./output/lowlevelboot/lowlevelboot.elf
          rm -rf ./output/lowlevelboot/lowlevelboot.hex
          rm -rf ./output/lowlevelboot/lowlevelboot.lst
          rm -rf ./output/lowlevelboot/lowlevelboot.map
          rm -rf ./output/mask_rom/mask_rom.elf
          rm -rf ./output/mask_rom/mask_rom.hex
          rm -rf ./output/mask_rom/mask_rom.lst
          rm -rf ./output/mask_rom/mask_rom.map
          rm -rf ./output/opensbi/fw_jump.elf
          rm -rf ./output/opensbi/fw_jump.lst
          rm -rf ./output/trusted_domain/trusted_fw.elf
          rm -rf ./output/trusted_domain/trusted_fw.hex
          rm -rf ./output/trusted_domain/trusted_fw.lst
          rm -rf ./output/trusted_domain/trusted_fw.map
          rm -rf ./output/uboot/u-boot.elf
          rm -rf ./output/uboot/u-boot.lst
          rm -rf ./output/uboot/u-boot.map
          mv ./quard_star_tools/gui_tools ./gui_tools
          tar -czf release_macos.tar.gz gui_tools/ output/ run.sh run_quard_star_tools.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: release_macos
          path: |
            release_macos.tar.gz

  test_macos:
    runs-on: macos-12
    needs: [release_macos]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release_macos

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install prerequisites
        run: |
          brew install libffi gettext glib pkg-config autoconf automake pixman ninja coreutils
          tar -xzvf release_macos.tar.gz

      - name: Run tests pflash boot
        shell: bash -l {0}
        run: |
          gtimeout --foreground -s SIGKILL 3m AUDIO_PARAM="-audiodev none,id=audio0" ./run.sh nographic default pfalsh > >(tee run_qemu.log) || {
            echo
            if cat run_qemu.log | grep "init process"
            then
              echo "Kernel boot successfully"
            else
              echo "Kernel boot failed"
              killall qemu-system-riscv64
              exit 1
            fi
            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
            then
              killall qemu-system-riscv64
              echo "Pass simulation"
            else
              killall qemu-system-riscv64
              echo "Failed in init process"
              exit 1
            fi
          }

      - name: Run tests sd boot
        shell: bash -l {0}
        run: |
          gtimeout --foreground -s SIGKILL 3m AUDIO_PARAM="-audiodev none,id=audio0" ./run.sh nographic default sd > >(tee run_qemu.log) || {
            echo
            if cat run_qemu.log | grep "init process"
            then
              echo "Kernel boot successfully"
            else
              echo "Kernel boot failed"
              killall qemu-system-riscv64
              exit 1
            fi
            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
            then
              killall qemu-system-riscv64
              echo "Pass simulation"
            else
              killall qemu-system-riscv64
              echo "Failed in init process"
              exit 1
            fi
          }

      - name: Run tests spi boot
        shell: bash -l {0}
        run: |
          gtimeout --foreground -s SIGKILL 5m AUDIO_PARAM="-audiodev none,id=audio0" ./run.sh nographic default spi > >(tee run_qemu.log) || {
            echo
            if cat run_qemu.log | grep "init process"
            then
              echo "Kernel boot successfully"
            else
              echo "Kernel boot failed"
              killall qemu-system-riscv64
              exit 1
            fi
            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
            then
              killall qemu-system-riscv64
              echo "Pass simulation"
            else
              killall qemu-system-riscv64
              echo "Failed in init process"
              exit 1
            fi
          }
